name: Build Chlaty CLI on Linux

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl    # Default 64-bit     # 32-bit
          - aarch64-unknown-linux-musl   # ARM64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install Cross Dependencies
        run: |
          sudo apt-get update
          sudo apt install musl-tools
          cargo install cross


      - name: Build CLI
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename chlaty-cli
        run: |
          mv target/${{ matrix.target }}/release/chlaty-cli target/${{ matrix.target }}/release/chlaty-cli-${{ matrix.target }}


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-chlaty-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/chlaty-cli-${{ matrix.target }}
