name: Build Chlaty CLI on macOS

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin     # Intel Macs
          - aarch64-apple-darwin    # Apple Silicon

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Build chlaty-cli
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename chlaty-cli
        run: |
          mv target/${{ matrix.target }}/release/chlaty-cli target/${{ matrix.target }}/release/chlaty-cli-${{ matrix.target }}


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-chlaty-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/chlaty-cli-${{ matrix.target }}
